### PR TITLE
Filemigration

### PR DESCRIPTION
**Pull request by mimikomp**
First & final merge into main branch

### CODE REVIEW

**Review by staceyjhlee — APPROVED** [review]
Great additions and adjustments to the app!

**Comment by mimikomp** [comment]
> Great additions and adjustments to the app!

Thanks! You too!

**Comment by mimikomp** [comment]
> Thanks! You too!

**Comment by itsHackinTime** [comment]
can you guys settle down im trying to merge this pull request

**Review by andrewmdai — APPROVED** [review]
Absolutely fantastic work! Looking forward to all your future projects!

**Comment by itsHackinTime** [comment]
> Absolutely fantastic work! Looking forward to all your future projects!

Hi wonderful work!

**Review by itsHackinTime — APPROVED** [review]
Looks good, keep up the great work! <3

**Pull request merged**
